### PR TITLE
Upgrade to 5.14.1

### PR DESCRIPTION
**Pull request by shr-project**

### CODE REVIEW

**Comment by shr-project** [comment]
@schnitzeltony FYI

**Comment by kraj** [comment]
seems to work ok on yoe distro /yoe-qt5-wayland-image

**Comment by shr-project** [comment]
Merged without the middle commit, because the 5.14.1 was merged to 5.14 branch now.

f13a3cec..23914740  master -> master

**Comment by schnitzeltony** [comment]
> @schnitzeltony FYI

Yes - saw that - thanks a lot

**Pull request closed without merging**
