### PR TITLE
qt5: upgrade to 5.12.8

### PR DESCRIPTION
**Pull request by migronof**
Signed-off-by: Mikko Gronoff <mikko.gronoff@qt.io>

### CODE REVIEW

**Comment by shr-project** [comment]
In warrior-next now, thanks.

**Comment by shr-project** [comment]
ERROR: Fetcher failure: Unable to find revision 194b584ca1381ab5c5bdebfb455901cf2b0bad61 in branch 5.12 even from upstream
ERROR: Fetcher failure for URL: 'git://code.qt.io/qt/qtmultimedia.git;name=qtmultimedia;branch=5.12;protocol=git'. Unable to fetch URL from any source.

**Comment by migronof** [comment]
Apologies (once again). I apparently can't assume that all modules would be fine if forward merge bot has been run on 5.12.8 branch and it has merged at least 4 modules successfully. I should've checked the fetch first and not assume. I'll reach for the branch merge folks to get that multimedia merge done as well.

**Comment by migronof** [comment]
qtmultimedia module has now been merged into 5.12

**Comment by shr-project** [comment]
Thanks, passed my "-c patch" now.

**Comment by shr-project** [comment]
In warrior now, thanks.

**Pull request closed without merging**
