### PR TITLE
added qml support to python

### PR DESCRIPTION
**Pull request by miccom86**
this patch enable qml and qtquick to pythonqt5

### CODE REVIEW

**Comment by shr-project** [comment]
Added to zeus-next, but please send your Signed-off-by tag and next time prefix the summary line with changed component in this case "python-pyqt5: "

**Comment by shr-project** [comment]
Also what about python-pyqt5_5.12.1.bb ? doesn't it need those dependencies as well?

**Comment by shr-project** [comment]
Yes python-pyqt5 fails to build with:
| Project ERROR: Unknown module(s) in QT: qml
will move the dependencies to python-pyqt5.inc where they belong.

**Comment by LocutusOfBorg** [comment]
thanks for merging!

**Pull request closed without merging**
