### PR TITLE
make qtbase and qtwebkit support arm32 BE.

### PR DESCRIPTION
**Pull request by leimaohui**
Make qtbase and qtwebkit support arm32 BE.

### CODE REVIEW

**Comment by otavio** [comment]
This must be send against the master branch. Then another PR doing the backport can be send.

**Comment by shr-project** [comment]
Added to master-next with few modifications, testing it now.

Once it's merged update your patches to match with what was merged to master and update this pull request.

**Comment by shr-project** [comment]
it's in master now, update this pull request for sumo as requested.

**Comment by otavio** [comment]
@shr-project I think we can rebase and merge this. Do you agree?

**Comment by shr-project** [comment]
Why should we when the submitter lost interest in supporting this?

**Comment by otavio** [comment]
Or we close this PR.  I am fine in closing it...

**Pull request closed without merging**
