### PR TITLE
qtwebengine: Fix build with clang-11

### PR DESCRIPTION
**Pull request by kraj**
Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by schnitzeltony** [comment]
Are these changes compatible with elder versions of ICU?

In meta-office I did something like [1]:

#ifndef TRUE
#   define TRUE  true
#endif

[1] https://github.com/schnitzeltony/meta-office/commit/174d12b8c8f677e120d77edfc827841ba83864e5

**Comment by kraj** [comment]
> Are these changes compatible with elder versions of ICU?
> 
> In meta-office I did something like [1]:
> 
> #ifndef TRUE
> 
> # define TRUE true
> #endif
> 
> [1] [schnitzeltony/meta-office@174d12b](https://github.com/schnitzeltony/meta-office/commit/174d12b8c8f677e120d77edfc827841ba83864e5)

meta-qt5 supports dedicated branches for releases, so right now master is only meant for master of core therefore we can assume that we will not use older ICU on master. If one needs older releases they should be using `gatesgarth` or `dunfell` branches

**Comment by schnitzeltony** [comment]
Sorry for being late - am working >12h/day currently - release panic...

Have an alternate - less intrusive - qtwebkit/icu fix under test. Are there still chances for that?

**Comment by kraj** [comment]
sure

**Comment by shr-project** [comment]
qtwebengine one merged:
To github.com:meta-qt5/meta-qt5.git
   217f87c1..83ab966e  master -> master

qtwebkit should be resolved through https://github.com/meta-qt5/meta-qt5/pull/374

**Pull request closed without merging**
