### PR TITLE
Fixes postgresql dependency

### PR DESCRIPTION
**Pull request by feddischson**
Removes postgresql from the native version.

Signed-off-by: Christian Haettich <feddischson@gmail.com>

### CODE REVIEW

**Comment by shr-project** [comment]
Fixed commit message and added to master-next.

**Comment by shr-project** [comment]
It's missing your Signed-off-by tag. Please add it at least here.

**Comment by feddischson** [comment]
Done

**Comment by shr-project** [comment]
5832bf2..3fa1993  master -> master

**Pull request closed without merging**
