### PR TITLE
qtwebengine: fix build with enabled external icu library

### PR DESCRIPTION
**Pull request by andy9a9**
- Add target/native icu dependencies only when system library using is enabled

### CODE REVIEW

**Comment by andy9a9** [comment]
> 
> 
> Target icu already depends on icu-native, so why is this needed?

Yes, but it isn't staged into webengine native sysroot, but into icu itself.
I have just enabled PACKAGECONFIG icu and saw this error.

**Comment by shr-project** [comment]
Does it fail without icu-native during do_configure or later in do_compile.

It did finish do_configure without this change and with icu PACKAGECONFIG enabled OK for me even without icu-i18n on host.

```
martin@jama:/OE/build/oe-core$ grep -B 3 icu tmp-glibc/work/core2-64-oe-linux/qtwebengine/5.14.99+5.15-beta3+gitAUTOINC+6b62dfe724_9424dc7cee-r0/temp/log.do_configure
Checking for fontconfig... yes
Checking for freetype >= 2.4.2... yes
Checking for glibc > 2.16... yes
Checking for icu >= 64... yes
--
    glibc ................................ yes
  Optional system libraries used:
    re2 .................................. no
    icu .................................. yes
martin@jama:/OE/build/oe-core$ find /usr -name icu-i18n\*
martin@jama:/OE/build/oe-core$ find tmp-glibc/work/core2-64-oe-linux/qtwebengine/5.14.99+5.15-beta3+gitAUTOINC+6b62dfe724_9424dc7cee-r0/recipe-sysroot* -name icu-i18n\*
tmp-glibc/work/core2-64-oe-linux/qtwebengine/5.14.99+5.15-beta3+gitAUTOINC+6b62dfe724_9424dc7cee-r0/recipe-sysroot/usr/lib/pkgconfig/icu-i18n.pc
```

**Comment by andy9a9** [comment]
It failed during do_compile, after 172/172 task.

Meanwhile, I have noticed, that is failing now.
```
| [12937/13304] CXX v8_snapshot/obj/v8/mksnapshot/mksnapshot.o
| FAILED: v8_snapshot/obj/v8/mksnapshot/mksnapshot.o
| /builds/ccp/meta-siemens/projects/systemone/tmp/hosttools/g++ -MMD -MF v8_snapshot/obj/v8/mksnapshot/mksnapshot.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DNO_TCMALLOC -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DOFFICIAL_BUILD -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -DTOOLKIT_QT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64 -DENABLE_MINOR_MC -DV8_INTL_SUPPORT -DV8_USE_SNAPSHOT -DV8_CONCURRENT_MARKING -DV8_TARGET_ARCH_ARM -DCAN_USE_ARMV7_INSTRUCTIONS -DCAN_USE_VFP3_INSTRUCTIONS -DCAN_USE_VFP32DREGS -DCAN_USE_NEON -DUSE_EABI_HARDFLOAT=1 -DUSING_SYSTEM_ICU=1 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC -Iv8_snapshot/gen -I../../../../git/src/3rdparty/chromium -I../../../../git/src/3rdparty/chromium/v8 -Iv8_snapshot/gen/v8 -Iv8_snapshot/gen -Iv8_snapshot/gen -I../../../../git/src/3rdparty/chromium/v8/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m32 -msse2 -mfpmath=sse -mmmx -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -fno-delete-null-pointer-checks -Wno-comments -Wno-dangling-else -Wno-packed-not-aligned -Wno-missing-field-initializers -Wno-unused-parameter -fno-omit-frame-pointer -gdwarf-3 -g1 -fvisibility=hidden -Wno-strict-overflow -Wno-return-type -O3 -fno-ident -fdata-sections -ffunction-sections -std=gnu++14 -Wno-narrowing -Wno-attributes -Wno-class-memaccess -Wno-subobject-linkage -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../../../git/src/3rdparty/chromium/v8/src/snapshot/mksnapshot.cc -o v8_snapshot/obj/v8/mksnapshot/mksnapshot.o
| In file included from ../../../../git/src/3rdparty/chromium/v8/src/snapshot/serializer.h:11,
|                  from ../../../../git/src/3rdparty/chromium/v8/src/snapshot/partial-serializer.h:9,
|                  from ../../../../git/src/3rdparty/chromium/v8/src/snapshot/mksnapshot.cc:15:
| ../../../../git/src/3rdparty/chromium/v8/src/isolate.h:36:10: fatal error: unicode/uversion.h: No such file or directory
|  #include "unicode/uversion.h"  // Define U_ICU_NAMESPACE.
|           ^~~~~~~~~~~~~~~~~~~~
| compilation terminated.
```

**Comment by andy9a9** [comment]
I have made a little progress on my side. It was trying to use bundled ICU even if a system one should be used.

qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/git/src/3rdparty/chromium/third_party/icu/BUILD.gn

```diff
config("system_icu_config") {
  defines = [
    "USING_SYSTEM_ICU=1",
    "ICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC",
  ]

+   include_dirs = [ "${target_sysroot}/usr/include" ]
}

if (use_system_icu) {
```

But after this it failed again on something different.
```
[50/5467] CXX host/obj/third_party/blink/renderer/platform/character_data_generator/character_property_data_generator.o
FAILED: host/obj/third_party/blink/renderer/platform/character_data_generator/character_property_data_generator.o 
/home/projects/DEV_CCP5/fs40i/build/tmp/hosttools/g++ -MMD -MF host/obj/third_party/blink/renderer/platform/character_data_generator/character_property_data_generator.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DNO_TCMALLOC -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DOFFICIAL_BUILD -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -DTOOLKIT_QT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DUSING_SYSTEM_ICU=1 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC -Ihost/gen -I../../../../git/src/3rdparty/chromium -Ihost/gen -Ihost/gen -I/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot/usr/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m64 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -fno-delete-null-pointer-checks -Wno-comments -Wno-dangling-else -Wno-packed-not-aligned -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g1 -fvisibility=hidden -isystem../../../../recipe-sysroot-native/usr/include -isystem../../../../recipe-sysroot-native/usr/include -std=gnu++14 -Wno-narrowing -Wno-attributes -Wno-class-memaccess -Wno-subobject-linkage -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -I/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot-native/usr/include -c ../../../../git/src/3rdparty/chromium/third_party/blink/renderer/platform/text/character_property_data_generator.cc -o host/obj/third_party/blink/renderer/platform/character_data_generator/character_property_data_generator.o
In file included from /home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot/usr/include/sys/cdefs.h:460,
                 from /home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot/usr/include/features.h:450,
                 from /home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot/usr/include/bits/libc-header-start.h:33,
                 from /home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot/usr/include/stdint.h:26,
                 from /home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot/usr/include/unicode/ptypes.h:68,
                 from /home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot/usr/include/unicode/umachine.h:46,
                 from /home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot/usr/include/unicode/utypes.h:38,
                 from /home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot/usr/include/unicode/uobject.h:22,
                 from ../../../../git/src/3rdparty/chromium/third_party/blink/renderer/platform/text/character_property_data_generator.h:8,
                 from ../../../../git/src/3rdparty/chromium/third_party/blink/renderer/platform/text/character_property_data_generator.cc:5:
/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot/usr/include/bits/wordsize.h:23:2: error: #error "__WORDSIZE is not defined"
 #error "__WORDSIZE is not defined"
  ^~~~~
/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot/usr/include/bits/wordsize.h:46:2: error: #error "Unknown __WORDSIZE detected"
 #error "Unknown __WORDSIZE detected"
  ^~~~~
```
@shr-project Could you please verify it, if unbounded icu using is working on your side?

**Comment by andy9a9** [comment]
I have put some debugs into icu building process.

```
make[3]: Leaving directory '/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/build/src/core'
( test -e Makefile.gn_run || /home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot-native/usr/bin/qmake -o Makefile.gn_run /home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/git/src/core/gn_run.pro CONFIG+=force_debug_info 'QMAKE_CXX=aarch64-ccp-linux-g++  -fstack-protector-strong  -D_FORTIFY_SOURCE=2  --sysroot=/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot' 'QMAKE_CC=aarch64-ccp-linux-gcc  -fstack-protector-strong  -D_FORTIFY_SOURCE=2  --sysroot=/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot' 'QMAKE_LINK=aarch64-ccp-linux-g++  -fstack-protector-strong  -D_FORTIFY_SOURCE=2  --sysroot=/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot' 'QMAKE_CFLAGS= -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0=/usr/src/debug/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0                      -fdebug-prefix-map=/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0=/usr/src/debug/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0                      -fdebug-prefix-map=/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot-native= ' 'QMAKE_CXXFLAGS= -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0=/usr/src/debug/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0                      -fdebug-prefix-map=/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0=/usr/src/debug/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0                      -fdebug-prefix-map=/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden' -after ) && make -f Makefile.gn_run 

["-s", "/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot", "-a", "arm64", "-p", "/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/build/src/core/pkg-config_wrapper.sh", "--system_libdir", "lib", "nss", "-v", "-lssl3"]

["-s", "/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot", "-a", "arm64", "-p", "/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/build/src/core/pkg-config_wrapper.sh", "--system_libdir", "lib", "icu-i18n"]
[["/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot/usr/include/nss3"], [], ["smime3", "nss3", "softokn3", "nssutil3", "plds4", "plc4", "nspr4", "pthread", "dl"], []]
[[], [], ["icui18n", "icuuc", "icudata"], []]

["-s", "/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot", "-a", "arm64", "-p", "/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/build/src/core/pkg-config_wrapper.sh", "--system_libdir", "lib", "icu-uc"]
[[], [], ["icuuc", "icudata"], []]

["-s", "/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot", "-a", "arm64", "-p", "/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/build/src/core/pkg-config_wrapper.sh", "--system_libdir", "lib", "libpng"]
[["/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot/usr/include/libpng16"], [], ["png16", "z"], []]

["-s", "/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot", "-a", "arm64", "-p", "/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/build/src/core/pkg-config_wrapper.sh", "--system_libdir", "lib", "libwebp", "libwebpmux", "libwebpdemux"]
[[], [], ["webpmux", "webpdemux", "webp"], []]

["-s", "/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot", "-a", "arm64", "-p", "/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/build/src/core/pkg-config_wrapper.sh", "--system_libdir", "lib", "dbus-1"]
[["/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot/usr/include/dbus-1.0", "/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot/usr/lib/dbus-1.0/include"], [], ["dbus-1"], []]

["-s", "/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot", "-a", "arm64", "-p", "/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/build/src/core/pkg-config_wrapper.sh", "--system_libdir", "lib", "freetype2"]
[["/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot/usr/include/freetype2"], [], ["freetype"], []]
ERROR at //third_party/icu/BUILD.gn:13:1: Assertion failed.
assert(!is_linux || host_toolchain != current_toolchain, "Trying to include icu for host build")
^-----
Trying to include icu for host build
See //third_party/blink/renderer/platform/BUILD.gn:145:5: which caused the file to be included.
    "//third_party/icu",
    ^------------------

["-p", "/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/build/src/core/pkg-config_wrapper.sh", "icu-i18n"]
[[], [], ["icui18n", "icuuc", "icudata"], []]

["-p", "/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/build/src/core/pkg-config_wrapper.sh", "icu-uc"]
[[], [], ["icuuc", "icudata"], []]

["-p", "/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot-native/usr/bin/pkg-config-native", "nss", "-v", "-lssl3"]
[["/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot-native/usr/lib/pkgconfig/../../../usr/include/nss3"], [], ["smime3", "nss3", "softokn3", "nssutil3", "plds4", "plc4", "nspr4", "pthread", "dl"], ["/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/recipe-sysroot-native/usr/lib/pkgconfig/../../../usr/lib"]]
make[2]: Leaving directory '/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/build/src/core'
make[1]: Leaving directory '/home/projects/DEV_CCP5/fs40i/build/tmp/work/aarch64t2-mx8-ccp-linux/qtwebengine/5.12.5+gitAUTOINC+dbc0d09be2_7a779d0160-r0/build/src'
```

So it's really trying to use a native icu. Is it ok?

**Comment by shr-project** [comment]
In master-next now for testing, thanks and sorry for delay.

**Comment by shr-project** [comment]
Merged, thanks (I forgot to change the subject prefix from icu: to qtwebengine:).

**Pull request closed without merging**
