### PR TITLE
Upgrade to 5.12.2

### PR DESCRIPTION
**Pull request by migronof**

### CODE REVIEW

**Comment by schnitzeltony** [comment]
FWIW: All layers on master I have started my world-build containing loads of Qt recipes from meta-qt5-exta/meta-musicians.

Thanks for updating and I will report results next week.

**Comment by shr-project** [comment]
In master-next.

**Comment by shr-project** [comment]
This PR breaks qtbase-native do_configure at least on ubuntu-18.04 hosts.

configure fails with:
ERROR: Feature 'system-zlib' was enabled, but the pre-condition 'libs.zlib' failed.

Checking for zlib...
Trying source 0 (type inline) of library zlib ...
  => source failed condition 'config.msvc'.
Trying source 1 (type inline) of library zlib ...
  => source failed condition 'config.msvc'.
Trying source 2 (type inline) of library zlib ...
None of [libz.so libz.a] found in [] and global paths.
  => source produced no result.
Trying source 3 (type inline) of library zlib ...
  => source failed condition 'config.wasm'.
test config.qtbase.libraries.zlib FAILED

while with current meta-qt5/master:

Checking for zlib...
Trying source 0 (type inline) of library zlib ...
  => source failed condition 'config.msvc'.
Trying source 1 (type inline) of library zlib ...
  => source failed condition 'config.msvc'.
Trying source 2 (type inline) of library zlib ...
+ cd /OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+13ed06640c-r0/build/config.tests/zlib && PKG_CONFIG_SYSROOT_DIR=/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+13ed06640c-r0/recipe-sysroot-native PKG_CONFIG_LIBDIR=/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+13ed06640c-r0/recipe-sysroot-native/usr/lib/pkgconfig /OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+13ed06640c-r0/build/bin/qmake "CONFIG -= qt debug_and_release app_bundle lib_bundle" "CONFIG += shared use_gold_linker warn_off console single_arch" -early "CONFIG += cross_compile" 'QMAKE_USE += zlib' 'QMAKE_LIBS_ZLIB = -lz' /OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+13ed06640c-r0/build/config.tests/zlib
+ cd /OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+13ed06640c-r0/build/config.tests/zlib && MAKEFLAGS= make
> g++  -c -pipe -isystem/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+13ed06640c-r0/recipe-sysroot-native/usr/include -O2 -pipe -O2 -w -fPIC  -I. -I/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+13ed06640c-r0/git/mkspecs/linux-oe-g++ -o main.o main.cpp
> g++  -L/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+13ed06640c-r0/recipe-sysroot-native/usr/lib                         -L/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+13ed06640c-r0/recipe-sysroot-native/lib                         -Wl,--enable-new-dtags                         -Wl,-rpath-link,/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+13ed06640c-r0/recipe-sysroot-native/usr/lib                         -Wl,-rpath-link,/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+13ed06640c-r0/recipe-sysroot-native/lib                         -Wl,-rpath,/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+13ed06640c-r0/recipe-sysroot-native/usr/lib                         -Wl,-rpath,/OE/build/oe-core/tmp-glibc/work/x86_64-linux/qtbase-native/5.12.0+gitAUTOINC+13ed06640c-r0/recipe-sysroot-native/lib                         -Wl,-O1 -Wl,-O1 -fuse-ld=gold -o zlib main.o   -lz
 => source accepted.
test config.qtbase.libraries.zlib succeeded
..
  Using system zlib ...................... yes

Possibly caused by:
commit e80bf655e922e9864f8843b5e7bbb47019a6d95a
Author: Oswald Buddenhagen <oswald.buddenhagen@qt.io>
Date:   Thu Dec 7 19:30:07 2017 +0100

    configure: verify header presence against sources

**Comment by migronof** [comment]
Ok, sapiippo found out the problem. Please try again with the added commit

**Comment by shr-project** [comment]
Added to master-next, thanks.

**Comment by schnitzeltony** [comment]
My builds finally finished. All the KDE/LXQt/Liri/Music ... recipes build fine.

**Comment by shr-project** [comment]
I see some runtime issues with LuneOS, but those might exist with 5.12.1 as well, so I'm not blocking this on that.

Merged to warrior and master branches.

**Comment by shr-project** [comment]
There is one more issue caused by using full paths to libraries, target qtbase is now failing in do_configure when xlib is enabled.

Not using libm at all or using -lm again fixes the config.test:

docker-shr @ ~/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/build/config.tests/xlib $ x86_64-oe-linux-g++  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot -Wl,-O1 -Wl,--hash-style=gnu -fstack-protector-strong -Wl,-z,relro,-z,now --sysroot=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot --sysroot=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot -Wl,-O1  -o xlib main.o   -L/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot/usr/lib /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot/usr/lib/libX11.so /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot/usr/lib/libXext.so /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot/usr/lib/libm.so
/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.3.0/ld: error: cannot open /lib/libm.so.6: No such file or directory
/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.3.0/ld: error: cannot open /usr/lib/libmvec_nonshared.a: No such file or directory
/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/8.3.0/ld: error: cannot open /lib/libmvec.so.1: No such file or directory
collect2: error: ld returned 1 exit status
docker-shr @ ~/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/build/config.tests/xlib $ x86_64-oe-linux-g++  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot -Wl,-O1 -Wl,--hash-style=gnu -fstack-protector-strong -Wl,-z,relro,-z,now --sysroot=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot --sysroot=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot -Wl,-O1  -o xlib main.o   -L/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot/usr/lib /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot/usr/lib/libX11.so /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot/usr/lib/libXext.so
docker-shr @ ~/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/build/config.tests/xlib $ x86_64-oe-linux-g++  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot -Wl,-O1 -Wl,--hash-style=gnu -fstack-protector-strong -Wl,-z,relro,-z,now --sysroot=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot --sysroot=/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot -Wl,-O1  -o xlib main.o   -L/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot/usr/lib /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot/usr/lib/libX11.so /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtbase/5.12.3+gitAUTOINC+b527725766-r0/recipe-sysroot/usr/lib/libXext.so -lm

**Pull request closed without merging**
