### PR TITLE
qt5: update to Qt 5.12.6

### PR DESCRIPTION
**Pull request by migronof**
Signed-off-by: Mikko Gronoff <mikko.gronoff@qt.io>

### CODE REVIEW

**Comment by shr-project** [comment]
In warrior-next for testing, thanks.

**Comment by shr-project** [comment]
Unfortunately doesn't build:
ERROR: qtbase-5.12.6+gitAUTOINC+f0b93f7a4b-r0 do_fetch: Fetcher failure: Unable to find revision f0b93f7a4b4281c5470280eb36b7c0ef5948a921 in branch 5.12 even from upst
ream

because the 5.12.6 wasn't downmerged to 5.12 yet:

qtbase$ git branch -a --contains v5.12.6
  remotes/origin/5.12.6

Can you please ask someone to do the downmerges to unblock this?

**Comment by shr-project** [comment]
And the same for e.g. qtdeclarative as well:
ERROR: qtdeclarative-native-5.12.6+gitAUTOINC+179c4b689d-r0 do_fetch: Fetcher failure: Unable to find revision 179c4b689d1a7b9e9edb71ddf545dc237bca6704 in branch 5.12 even f|
rom upstream

**Comment by shr-project** [comment]
And pretty much all other recipes as well:
ERROR: qt3d-native-5.12.6+gitAUTOINC+b77712dd95-r0 do_fetch: Fetcher failure: Unable to find revision b77712dd95adb6644e9af3bf98a2a6ebc5a52ec4 in branch 5.12 even from upstream
ERROR: qtcanvas3d-5.12.6+gitAUTOINC+51e8dc59d8-r0 do_fetch: Fetcher failure: Unable to find revision 51e8dc59d87463f32dab0e401e9ae17615c7b790 in branch 5.12 even from upstream
ERROR: qtcharts-5.12.6+gitAUTOINC+969fc5bf94-r0 do_fetch: Fetcher failure: Unable to find revision 969fc5bf94e8e0e6cd86c79c38e11074de235273 in branch 5.12 even from upstream
ERROR: qtconnectivity-5.12.6+gitAUTOINC+33f5988ead-r0 do_fetch: Fetcher failure: Unable to find revision 33f5988eadf1b748d75deec8bc12afc1d47ea52f in branch 5.12 even from upstream
ERROR: qtdatavis3d-5.12.6+gitAUTOINC+2b753d7caa-r0 do_fetch: Fetcher failure: Unable to find revision 2b753d7caa9f780d6a76829db516e3fb859c3353 in branch 5.12 even from upstream
ERROR: qtgamepad-5.12.6+gitAUTOINC+39b7df80c9-r0 do_fetch: Fetcher failure: Unable to find revision 39b7df80c9b58dffc7a6e9e68b99e1b9f78ed2e0 in branch 5.12 even from upstream
ERROR: qtimageformats-5.12.6+gitAUTOINC+dad286f15b-r0 do_fetch: Fetcher failure: Unable to find revision dad286f15b75f36f37d4523ac86696e5133e58cb in branch 5.12 even from upstream
ERROR: qtlocation-5.12.6+gitAUTOINC+ad359c55d3_4b85252fbe-r0 do_fetch: Fetcher failure: Unable to find revision ad359c55d36f39c7f243bee8960d490772bfe84e in branch 5.12 even from upstream
ERROR: qtmultimedia-5.12.6+gitAUTOINC+53a507b30b-r0 do_fetch: Fetcher failure: Unable to find revision 53a507b30befc40a4d06a1620e85bb4a5b1bf40a in branch 5.12 even from upstream
ERROR: qtnetworkauth-5.12.6+gitAUTOINC+ecdeaac31d-r0 do_fetch: Fetcher failure: Unable to find revision ecdeaac31d2cdebda5d7b06a0224fd34649a7375 in branch 5.12 even from upstream
ERROR: qtpurchasing-5.12.6+gitAUTOINC+ceb003e074-r0 do_fetch: Fetcher failure: Unable to find revision ceb003e074cdbb6f2429dd3f4ddcf995382d199e in branch 5.12 even from upstream
ERROR: qtquickcontrols-5.12.6+gitAUTOINC+8f8d9b7015-r0 do_fetch: Fetcher failure: Unable to find revision 8f8d9b7015cd05e936d560f097cbce42eb375de9 in branch 5.12 even from upstream
ERROR: qtquickcontrols2-5.12.6+gitAUTOINC+ed92154c71-r0 do_fetch: Fetcher failure: Unable to find revision ed92154c712b0e54caa5baa72d832d7f8286307f in branch 5.12 even from upstream
ERROR: qtremoteobjects-5.12.6+gitAUTOINC+76d6a13889-r0 do_fetch: Fetcher failure: Unable to find revision 76d6a13889514b03a1878e19b56eb1e6f17d1b90 in branch 5.12 even from upstream
ERROR: qtscript-5.12.6+gitAUTOINC+c2e02e863c-r0 do_fetch: Fetcher failure: Unable to find revision c2e02e863c3867f5d038731f429cc3a03f3cc3bc in branch 5.12 even from upstream
ERROR: qtscxml-native-5.12.6+gitAUTOINC+9ed16e4621-r0 do_fetch: Fetcher failure: Unable to find revision 9ed16e4621ae705947d5e04ade450f1859ef86c5 in branch 5.12 even from upstream
ERROR: qtsensors-5.12.6+gitAUTOINC+8fd13b71e5-r0 do_fetch: Fetcher failure: Unable to find revision 8fd13b71e50d0935af69e70f1961ac8194cb6fb3 in branch 5.12 even from upstream
ERROR: qtserialbus-5.12.6+gitAUTOINC+4347caecbd-r0 do_fetch: Fetcher failure: Unable to find revision 4347caecbd0b2d02074a033eabf7d114ad7ca5f6 in branch 5.12 even from upstream
ERROR: qtserialport-5.12.6+gitAUTOINC+f3bf6e0cc9-r0 do_fetch: Fetcher failure: Unable to find revision f3bf6e0cc9c7b8c9d1ef249cf8043c465d7e8186 in branch 5.12 even from upstream
ERROR: qtsvg-5.12.6+gitAUTOINC+f8eb5228da-r0 do_fetch: Fetcher failure: Unable to find revision f8eb5228da5805161701477682489baf9d5028ea in branch 5.12 even from upstream
ERROR: qttools-native-5.12.6+gitAUTOINC+c4988ca213-r0 do_fetch: Fetcher failure: Unable to find revision c4988ca21346752e601df8a6b2cef3ee10c062f0 in branch 5.12 even from upstream
ERROR: qtvirtualkeyboard-5.12.6+gitAUTOINC+73259adb59-r0 do_fetch: Fetcher failure: Unable to find revision 73259adb59f15dab266504f5444c99a6e06a7f32 in branch 5.12 even from upstream
ERROR: qtwayland-native-5.12.6+gitAUTOINC+b28b121f05-r0 do_fetch: Fetcher failure: Unable to find revision b28b121f05caba25da9544b31059832e0a492eef in branch 5.12 even from upstream
ERROR: qtwebchannel-5.12.6+gitAUTOINC+77af92deff-r0 do_fetch: Fetcher failure: Unable to find revision 77af92deffa9aeb8a5f85f1e73c3f110d24f7f40 in branch 5.12 even from upstream
ERROR: qtwebengine-5.12.6+gitAUTOINC+636b32c7f2_89644ad92f-r0 do_fetch: Fetcher failure: Unable to find revision 636b32c7f22c96e9562270219cedca52d5203737 in branch 5.12 even from upstream
ERROR: qtwebglplugin-5.12.6+gitAUTOINC+560f3c6f9a-r0 do_fetch: Fetcher failure: Unable to find revision 560f3c6f9a5e199f88be2f111e1ee5fa19948d57 in branch 5.12 even from upstream
ERROR: qtwebsockets-5.12.6+gitAUTOINC+fd32491102-r0 do_fetch: Fetcher failure: Unable to find revision fd324911025d49b8b3d89a155ce38e3228edfd33 in branch 5.12 even from upstream
ERROR: qtwebview-5.12.6+gitAUTOINC+bc7e946f0e-r0 do_fetch: Fetcher failure: Unable to find revision bc7e946f0e823be99de7834a2784c22d5ae2d628 in branch 5.12 even from upstream
ERROR: qtx11extras-5.12.6+gitAUTOINC+547506f904-r0 do_fetch: Fetcher failure: Unable to find revision 547506f904a2ba72d56c2c61c2c24adea91bdd25 in branch 5.12 even from upstream
ERROR: qtxmlpatterns-native-5.12.6+gitAUTOINC+e74c6fee10-r0 do_fetch: Fetcher failure: Unable to find revision e74c6fee102c228da060f3899610e4449bc1851a in branch 5.12 even from upstream

I guess you were testing it with nobranch=1 somewhere, but as explained before that is unacceptable for meta-qt5.

**Comment by migronof** [comment]
Yes, I had the nobranch=1 enabled.
Sorry about this, I've done this same thing before when I didn't check if the branches were merged. It may also be that the merges have been slightly delayed as some of the people doing those are at the Contributors' Summit this week.

**Comment by shr-project** [comment]
The branches were finally down-merged on 9th Jan, I've merged this to warrior now. Thanks

**Pull request closed without merging**
