### PR TITLE
qtbase: Fix for OpenSSLV3

### PR DESCRIPTION
**Pull request by dwalkes**
From lts 5.15.11-lts-lgpl and [1].

Resolves error:
```
QSslSocket: cannot call unresolved function SSL_get_peer_certificate
```

1: https://code.qt.io/cgit/qt/qtbase.git/commit/?h=v5.15.11-lts-lgpl&id=40c11752580802521d2fa10e4e036df61083ca42

See related discussion in https://github.com/meta-qt5/meta-qt5/pull/533

### CODE REVIEW

**Comment by dolcini** [comment]
@shr-project @otavio : any plan to merge this?

**Review by dolcini — APPROVED** [review]
LGTM (and also pretty much needed on kirkstone where a newer OpenSSL version is used)

**Comment by otavio** [comment]
Has it been fixed in master?

**Comment by dolcini** [comment]
qtbase in master is currently at version 5.15.9, while this issue was fixed in 5.15.11.

I assume we would want a different solution in master, e.g. bump to 5.15.x with x>=11.

**Comment by otavio** [comment]
Seems so.

**Comment by dolcini** [comment]
@otavio : is having master fixed before kirkstone a requirement here?

**Comment by otavio** [comment]
Yes, we need to fix `master` before `kirkstone` to ensure we never miss any fixes.

**Comment by dolcini** [comment]
@dwalkes : planning to send a PR to fix master? As @otavio wrote this is a prerequisite to get this merged.

**Comment by dwalkes** [comment]
@otavio @dolcini thanks for reviewing

> I assume we would want a different solution in master, e.g. bump to 5.15.x with x>=11.

I can work on a new PR to target 5.15.12-lts-lgpl on master today.

**Comment by dwalkes** [comment]
I see now it looks like there's already one in progress to 5.15.11 at https://github.com/meta-qt5/meta-qt5/pull/548/files

**Comment by dwalkes** [comment]
@otavio @dolcini I think the update for master is complete so this is ready to merge. Let me know if you need anything else.

**Pull request merged**
