### PR TITLE
layer.conf: set LAYERSERIES_COMPAT with honister

### PR DESCRIPTION
**Pull request by kkang-wr**
Set LAYERSERIES_COMPAT with honister and remove old codenames.

Signed-off-by: Kai Kang <kai.kang@windriver.com>

### CODE REVIEW

**Comment by schnitzeltony** [comment]
Why remove the old releases?

**Comment by kkang-wr** [comment]
Hi @schnitzeltony,

The original problem is that the value of LAYERSERIES_COMPAT is too long which causes layer index complains:
`WARNING: YPCompatibleVersion.name: dunfell gatesgarth hardknott: length 28 exceeds maximum (25), truncating`

Then I think it should align with oe-core which has only honister in layer.conf because it has branch hardknott too in meta-qt5. 
I did the same thing for meta-opemembedded. But Martin comments just now that it is too early to claim honister support.  And I'll withdraw this commit for now.

What's policy for meta-qt5? Would it be ok to claim to support the latest 2 releases(hardknott and honister for this case)?

Regards,
Kai

**Comment by schnitzeltony** [comment]
> The original problem is that the value of LAYERSERIES_COMPAT is too long which causes layer index complains:
WARNING: YPCompatibleVersion.name: dunfell gatesgarth hardknott: length 28 exceeds maximum (25), truncating

I think this is something to be fixed at layerindex

> What's policy for meta-qt5? Would it be ok to claim to support the latest 2 releases(hardknott and honister for this case)?

Don't know anything about policies but meta-qt5 master (and hardknott) are somewhat special because they have the last Qt5 5.15 versions in. And at least few weeks ago meta-qt5's master worked perfectly fine in dunfell environment e.g https://github.com/meta-qt5/meta-qt5/commit/08550c223c4528ed76d45a981aff65c8857b9195 was created in such environment

**Comment by kkang-wr** [comment]
Got it. Thanks a lot.

**Pull request closed without merging**
