### PR TITLE
qtbase: Add licenses for third party included components

### PR DESCRIPTION
**Pull request by cbs101**
Qtbase contains a bunch of include software. See:
https://doc.qt.io/qt-5/licenses-used-in-qt.html

Looked through the qtbase git, and through all the licenses.
Each license file has been added to LIC_FILES_CHKSUM.
For each license file, I looked at what license it was and added it to
LICENSE if not already present.

Each file with license obtained:
W3C    file://tests/auto/corelib/serialization/qxmlstream/XML-Test-Suite-LICENSE.txt;md5=bf8f4361abd6f81bfab9de61c237207d
SKIP    file://src/tools/moc/util/licenseheader.txt;md5=907c3cecc6bdaf76231ae4e3d1c1441b
BSD-4-CLAUSE    file://src/testlib/3rdparty/VALGRIND_LICENSE.txt;md5=87e865bb81ae3ea0f7c6215c6d366cc4
MIT    file://src/testlib/3rdparty/CYCLE_LICENSE.txt;md5=3fced11d6df719b47505837a51c16ae5
GPL-2.0    file://src/testlib/3rdparty/LINUX_LICENSE.txt;md5=ac2db169b9309e240555bc77be4f1a33
AFL-2.1    file://src/dbus/LIBDBUS-1-LICENSE.txt;md5=46ee5f692b0418273436d66f7b5a0264
(IJG & BSD-3-Clause & Zlib)    file://src/3rdparty/libjpeg/LICENSE;md5=2a423a921d0f68082c80ccc7ad808ef2
MIT    file://src/3rdparty/forkfd/LICENSE;md5=02656dcdfd1514ed340786527775e781
BitstreamVera    file://src/3rdparty/wasm/VERA-LICENSE;md5=38f6dde428987de48e1f4e11105e32c6
BitstreamVera    file://src/3rdparty/wasm/DEJAVU-LICENSE;md5=449b2c30bfe5fa897fe87b8b70b16cfa
MIT    file://src/3rdparty/angle/src/common/third_party/smhasher/LICENSE;md5=0d948322ab524e2b74f55eb8ef57c74a
MIT    file://src/3rdparty/angle/src/third_party/libXNVCtrl/LICENSE;md5=9e6c209899aa4986d090320bbca2fc76
BSD-2-Clause    file://src/3rdparty/angle/src/third_party/compiler/LICENSE;md5=0353c43961ee447c6432ea5c16485528
BSD-2-Clause    file://src/3rdparty/angle/SYSTEMINFO_LICENSE;md5=c1dd618e127b73bd8a52b08aebf0e6e7
BSD-3-Clause    file://src/3rdparty/angle/LICENSE;md5=10305d79487367a5e938772c27246ac1
BSD-3-Clause    file://src/3rdparty/angle/TRACEEVENT_LICENSE;md5=aebf2ec8c5999a97ebd0fb413845a09a
BSD-3-Clause    file://src/3rdparty/double-conversion/LICENSE;md5=1ea35644f0ec0d9767897115667e901f
Apache-2.0    file://src/3rdparty/android/LICENSE;md5=4c3b4cb87cfc8ccba69d579fbd7b0fb3
Free?    file://src/3rdparty/wintab/LICENSE.txt;md5=cfa9fd5f130c682cba5914f81e89689a
Zlib    file://src/3rdparty/zlib/LICENSE;md5=370cf821bfe014e4427629dab445adcf
BSD-3-Clause    file://src/3rdparty/easing/LICENSE;md5=4412f1b262a9e6f1e9fe4ade85b75b05
MIT    file://src/3rdparty/tinycbor/LICENSE;md5=6c1ac30774dd6476b42b5b020cd2aa5f
MIT    file://src/3rdparty/pixman/LICENSE;md5=6b664fb38b7394214286326147fe9a35
BSD-3-Clause    file://src/3rdparty/freebsd/LICENSE;md5=f8c580f998e1d7c217bab9f1b93fb313
Apache-2.0    file://src/3rdparty/gradle/LICENSE-GRADLEW.txt;md5=01aed3ac764d0bdeabc874b38adc9832
BSD-3-Clause    file://src/3rdparty/iaccessible2/LICENSE;md5=162feade06c5e3708a976b21c5bce9bd
MIT    file://src/3rdparty/xcb/LICENSE;md5=47464835c9e592c5675ff398f37be7cc
libpng    file://src/3rdparty/libpng/LICENSE;md5=b0085051bf265bac2bfc38bc89f50000
MIT    file://src/3rdparty/md4c/LICENSE.md;md5=a9bb255d25ad05f7d98d776cb2de4252
MIT    file://src/3rdparty/VulkanMemoryAllocator/LICENSE.txt;md5=762035fa7cfae632cd5297e05aac6b82
BSD-2-Clause    file://src/3rdparty/sha3/BRG_ENDIAN_LICENSE;md5=4de905da0171b13f239e935cdbf0216b
CC0-1.0    file://src/3rdparty/sha3/CC0_LICENSE;md5=c7c94ad80d36ac93a6f1c6c06fea50a5
Zlib    file://src/3rdparty/freetype/ZLIB-LICENSE.txt;md5=21441c9109f40d65ffa61fc104f2f58e
(Freetype & GPL-2.0)   file://src/3rdparty/freetype/LICENSE.txt;md5=7c1ac8006fa8b34a503dab33bd8f86b0
MIT    file://src/3rdparty/freetype/PCF-LICENSE.txt;md5=e0f11f550450e58753f2d54ddaf17d34
(Freetype & GPL-2.0)   file://src/3rdparty/freetype/docs/LICENSE.TXT;md5=4af6221506f202774ef74f64932878a1
MIT    file://src/3rdparty/freetype/BDF-LICENSE.txt;md5=d0c2c2e2e102c393a12869bc34515be2
Free?    file://src/3rdparty/icc/LICENSE.txt;md5=b6ca87da5b0eabd3ffa99442fb52a554
BSD-3-Clause    file://src/3rdparty/rfc6234/LICENSE;md5=d22b01d70caa846b5dca2f58e79136b4
BSD-3-Clause    file://src/plugins/platforms/cocoa/COCOA_LICENSE.txt;md5=bbbb2ebddd37416711539c36bf07e2a0
BSD-3-Clause    file://src/corelib/kernel/QEVENTDISPATCHER_CF_LICENSE.txt;md5=bbbb2ebddd37416711539c36bf07e2a0
Unicode    file://src/corelib/text/UNICODE_LICENSE.txt;md5=41e5cf226189186e47e89b8b6501c625
BSD-2-Clause    file://src/corelib/codecs/QEUCJPCODEC_LICENSE.txt;md5=53147b4fbe217f853a3f23d7a11dc240
BSD-2-Clause    file://src/corelib/codecs/QTSCIICODEC_LICENSE.txt;md5=f36a16de69d08da0af83ce2a672d8972
BSD-2-Clause    file://src/corelib/codecs/QEUCKRCODEC_LICENSE.txt;md5=4eeefaaf968e3bf0d8c901034241b172
BSD-2-Clause    file://src/corelib/codecs/QJISCODEC_LICENSE.txt;md5=53147b4fbe217f853a3f23d7a11dc240
BSD-2-Clause    file://src/corelib/codecs/QSJISCODEC_LICENSE.txt;md5=53147b4fbe217f853a3f23d7a11dc240
BSD-2-Clause    file://src/corelib/codecs/QBIG5CODEC_LICENSE.txt;md5=231d53acf3743a766ed8f60951028c07
BSD-2-Clause    file://src/corelib/codecs/QBKCODEC_LICENSE.txt;md5=30c522f2112f3ea350bc2afd96db7250
MPL-2.0    file://src/corelib/io/PSL-LICENSE.txt;md5=f75d2927d3c1ed2414ef72048f5ad640
(BSD-2-Clause & Imlib2)    file://src/gui/painting/QIMAGETRANSFORM_LICENSE.txt;md5=4c07743b9d2258a821de54f44c0ede1e
MIT    file://src/gui/painting/XCONSORTIUM_LICENSE.txt;md5=4d9cf5fb68f7b53d9d3d4861ea2f4389
BSD-3-Clause    file://src/gui/text/AGLFN_LICENSE.txt;md5=93e8ba826597a64fc27e4d374accaff4
MIT    file://src/gui/opengl/KHRONOS_LICENSE.txt;md5=7ef0bdfdb5fd7c1e9bb4d1fe5f41b45a
MIT    file://src/gui/vulkan/KHRONOS_LICENSE.txt;md5=ff94e83bfacfb929b78bdceec584cc58
MIT    file://util/gradientgen/WEBGRADIENTS_LICENSE.txt;md5=405e6c669ccba51c7730378d9503d0e6

Disclaimer: I am not a lawyer so I might have misunderstood certain licenses.

### CODE REVIEW

**Comment by cbs101** [comment]
If accepted, i'll continue the work on the rest  of the qt recipes. But will await the first one to be accepted first :)

A little unsure of the optimal format of all the extra licenses. Currently they are just listed as the order in which "find" found them. I can e.g. group them such that
LICENSE += "& BSD-2-Clause"
LIC_FILES_CHKSUM += "<all components with BSD-2-Clause"
LICENSE += "& MIT"
LIC_FILES_CHKSUM += "<all components with MIT>"

Would you prefer that ?

**Comment by cbs101** [comment]
Another idea could be change do_populate_lic(), such that the licences are acquire automatically using the "qt_attribution.json" files.
Loop through the qt_attribution.json files, and add to LICENSE and LIC_FILES_CHKSUM automatically.
This cannot be seen if dumping the environment using "bitbake -e", but makes it a bit easier to maintain qt...

**Comment by shr-project** [comment]
This is interesting topic, but I haven't merged it to master-next yet, because many of those 3rdparty licenses aren't AFAIK actually applicable as long as we use e.g. system freetype (which is in the default PACKAGECONFIG).

I agree that listing them all might be better to be safe, but something conditional on PACKAGECONFIGs would be nice as well or something like suggested qt_attribution.json.

As neither you or me are lawyers, have you tried to report this to The Qt Company? They surely have some lawyers available and will need to resolve the same for meta-qt6 as well.

**Comment by cbs101** [comment]
Hi

I'm unsure whether we can avoid listing licenses if they are not applicable, as you described with freetype.
E.g.: For all qt recipes, we always list both commercial and the GPL versions, even though it is either commercial or GPL. Listed as '|' in LICENSE.

Send a email to the yocto mailinglist, here:
https://lists.yoctoproject.org/g/licensing/topic/question_regarding_licenses/76986633?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,76986633
It is not just meta-qt5 that has this problem. Meta-browser also has it, and actually, a lot more recipes also contain third party software. Once you start looking, you seem to find more and more. E.g. e2fsprogs 1.45.4 has gettext 0.14.1 included. 
Hoped someone with knowledge about licensing had information about what todo with third party included software. But so far, noone has replied ..

I'll try writing a question to qt. 
Furthermore, i'll try to send a patch to meta-poky license.bbclass that allows a hook that could be used to obtain all the third party licenses used.
I would really dislike, if we needed to go through each recipe whenever new software arrives and manually obtain the third party components included. Hoping that by sending a MR with that hook to meta-poky will trigger some discussion about what todo..

**Comment by shr-project** [comment]
> I'm unsure whether we can avoid listing licenses if they are not applicable, as you described with freetype.
> E.g.: For all qt recipes, we always list both commercial and the GPL versions, even though it is either commercial or GPL. Listed as '|' in LICENSE.

But this example is different, you always build the code which is either commercial or GPL, but you can delete whole 3rdparty/freetype and still build qtbase fine as long as you use system freetype (which is the default behavior).

In some recipes we even did remove such 3rdparty software in do_configure_prepend (sometimes depending on selected PACKAGECONFIG) options to make sure that it doesn't get used accidentally (e.g. some other part including file from this 3rdparty directory). This could be extended to either add the license to LICENSE or remove the 3rdparty source completely.

But that's a lot of maintenance work and I did it only for a few recipes where the actual issue was highlighted by Black Duck or other tools.
 
> Send a email to the yocto mailinglist, here:
> https://lists.yoctoproject.org/g/licensing/topic/question_regarding_licenses/76986633?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,76986633
> It is not just meta-qt5 that has this problem. Meta-browser also has it, and actually, a lot more recipes also contain third party software. Once you start looking, you seem to find more and more. E.g. e2fsprogs 1.45.4 has gettext 0.14.1 included.
> Hoped someone with knowledge about licensing had information about what todo with third party included software. But so far, noone has replied ..

I've seen it and we even discussed it in OE TSC, I'm sorry nobody replied, I guess it's just to scary closet to start looking for skeletons now :)

> I'll try writing a question to qt.
> Furthermore, i'll try to send a patch to meta-poky license.bbclass that allows a hook that could be used to obtain all the third party licenses used.
> I would really dislike, if we needed to go through each recipe whenever new software arrives and manually obtain the third party components included. Hoping that by sending a MR with that hook to meta-poky will trigger some discussion about what todo..

I think one of the suggestions was to use something like
http://git.yoctoproject.org/cgit/cgit.cgi/meta-spdxscanner/
but not on the sources in S, but on the debug sources in PN-dbg which should be at least partially filtered on what you actually do use in the end.

This could be great as optional QA check to see if your specific setup (mostly PACKAGECONFIG combination) has some issue, but then to fix it in the recipe we would still need to add the licenses conditionally based on the configuration (which goes back to list-license-or-remove-the-source approach)

**Comment by cbs101** [comment]
Thanks for the fast response. Glad to hear it being discussed in OE TSC :)

I was not aware of any recipes that does cleanup and hence made PN-dbg more "correct". My newbie green eyes simply thought it would be fairly easy to hook into do_populate_lic() by something like:
Defining a placeholder function like:
  def <foobar>(info):
    return info

And then in do_populate_lic(), call that function just after get_recipe_info(), hence allow that <foobar> function to append to the info object.

Custom function could then be made for qt in a common class that would loop through the sources and look for the qt_attribution.json files.
For qtwebengine, that function would need to be extended even further to also allow looking for README.chromium files

**Comment by shr-project** [comment]
Qt5 is dead please follow up with TQC for their meta-qt6 if you're still interested.

**Pull request closed without merging**
