### PR TITLE
python3-pyqt5: Update to dev2008081558 snapshot

### PR DESCRIPTION
**Pull request by kraj**
Old one is gone see https://www.riverbankcomputing.com/software/pyqt/download5

### CODE REVIEW

**Comment by shr-project** [comment]
In master-next for testing.

**Comment by shr-project** [comment]
The commit "libconnman-qt5: Fix build errors found wih clang-11" causes following failure with glibc:

```
/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/libconnman-qt5/1.2.34+gitAUTOINC+a0b6b0d9a6-r0/recipe-sysroot/usr/include/QtDBus/qdbusargument.h: In instantiation of 'const QDBusArgument& operator>>(const QDBusArgument&, QList<T>&) [with T = RouteStructure]':
/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/libconnman-qt5/1.2.34+gitAUTOINC+a0b6b0d9a6-r0/recipe-sysroot/usr/include/QtDBus/qdbusargument.h:163:9:   required from 'T qdbus_cast(const QDBusArgument&, T*) [with T = QList<RouteStructure>]'
../../git/libconnman-qt/marshalutils.cpp:113:98:   required from here
/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/libconnman-qt5/1.2.34+gitAUTOINC+a0b6b0d9a6-r0/recipe-sysroot/usr/include/QtDBus/qdbusargument.h:276:13: error: ambiguous overload for 'operator>>' (operand types are 'const QDBusArgument' and 'RouteStructure')
  276 |         arg >> item;
      |         ~~~~^~~~~~~
../../git/libconnman-qt/marshalutils.cpp:39:36: note: candidate: 'const QDBusArgument& operator>>(const QDBusArgument&, RouteStructure&)'
   39 | Q_DBUS_EXPORT const QDBusArgument &operator>>(const QDBusArgument &a, RouteStructure &v);
      |                                    ^~~~~~~~
../../git/libconnman-qt/marshalutils.cpp:61:22: note: candidate: 'const QDBusArgument& {anonymous}::operator>>(const QDBusArgument&, RouteStructure&)'
   61 | const QDBusArgument &operator>>(const QDBusArgument &argument, RouteStructure &routestruct)
      |                      ^~~~~~~~
In file included from ../../recipe-sysroot/usr/include/QtDBus/QDBusMetaType:1,
                 from ../../git/libconnman-qt/marshalutils.cpp:34:
../../recipe-sysroot/usr/include/QtDBus/qdbusmetatype.h: In instantiation of 'void qDBusMarshallHelper(QDBusArgument&, const T*) [with T = RouteStructure]':
../../recipe-sysroot/usr/include/QtDBus/qdbusmetatype.h:81:12:   required from 'int qDBusRegisterMetaType(T*) [with T = RouteStructure]'
../../git/libconnman-qt/marshalutils.cpp:192:43:   required from here
../../recipe-sysroot/usr/include/QtDBus/qdbusmetatype.h:68:7: error: ambiguous overload for 'operator<<' (operand types are 'QDBusArgument' and 'const RouteStructure')
   68 | { arg << *t; }
      |   ~~~~^~~~~
../../git/libconnman-qt/marshalutils.cpp:40:30: note: candidate: 'QDBusArgument& operator<<(QDBusArgument&, const RouteStructure&)'
   40 | Q_DBUS_EXPORT QDBusArgument &operator<<(QDBusArgument &a, const RouteStructure &v);
      |                              ^~~~~~~~
../../git/libconnman-qt/marshalutils.cpp:46:16: note: candidate: 'QDBusArgument& {anonymous}::operator<<(QDBusArgument&, const RouteStructure&)'
   46 | QDBusArgument &operator<<(QDBusArgument &argument, const RouteStructure &routestruct)
      |                ^~~~~~~~
```

I'll drop this one from master-next until above issue is resolved.

**Comment by kraj** [comment]
@shr-project I have updated the patch such it that it only applies when using clang-11+

**Comment by shr-project** [comment]
In master now
   5144a99a..23f78f70  master -> master

**Pull request closed without merging**
