### PR TITLE
qtwebengine: Fix build with ninja >= 1.10.0

### PR DESCRIPTION
**Pull request by schnitzeltony**
* For now just skip version check. Looked into: ninja came from meta-oe to
  oe-core with:
  commit fc3aef67a95a90e9a485c6b0e93db8cdeab5d3ab
  Author: Khem Raj <raj.khem@gmail.com>
  Date:   Thu Jul 27 21:52:12 2017 -0700

      ninja: Add recipe

      llvm is using it, therefore move it from meta-oe

      Signed-off-by: Khem Raj <raj.khem@gmail.com>

  That was in rocko release cycle. So the assumption we have a ninja decent
  enough should be acceptable.
* Looked into qtwebengine current dev branch: There is no solution yet. So as
  soon as upstream offers a better solution most likely this patch will not
  apply any more and has to be removed then.

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>

### CODE REVIEW

**Comment by shr-project** [comment]
Is this error shown in log.do_configure? It seems to work for me without this patch:
```
Qt WebEngine Build Tools:
  Use System Ninja ....................... yes
  Use System Gn .......................... no
```

**Comment by schnitzeltony** [comment]
oe-coe upgraded ninja to 1.10 [1] and after that configure failed with

> Ninja version too old

This is no surprise if you look at their regex:

> contains(version, "1.[7-9].*"): return(true)

Is [1] already in your builds?

[1] https://github.com/openembedded/openembedded-core/commit/d1cd957cea29f3ab111ae752bc9ad75a1324c255

**Comment by shr-project** [comment]
Rebuilding with master now to check. If that's the case then I'll update commit message to mention this commit, because the one from meta-oe/rocko confused me :).

**Comment by schnitzeltony** [comment]
Thanks and sorry: was not my best commit message ever...

**Comment by shr-project** [comment]
I was able to reproduce it and updated version is now in master-next.

Thanks!

**Comment by schnitzeltony** [comment]
Applied 3e759d827722de6fddc9449f1149137021f4e25e

**Pull request closed without merging**
