### PR TITLE
Upgrade to Qt 5.12.3

### PR DESCRIPTION
**Pull request by shr-project**
@migronof @sapiippo Can you please check why v5.12.3 tags weren't created yet in those 3 modules?

### CODE REVIEW

**Comment by shr-project** [comment]
Also v5.12.3 in qttools repository isn't included in 5.12 branch yet.

**Comment by shr-project** [comment]
a4bf2402..eb5d6daa  master -> master
   a4bf2402..eb5d6daa  warrior -> warrior

**Comment by migronof** [comment]
Hi,
all the v5.12.3 tags should be in place now & all modules merged from 5.12.3 into 5.12 soon (last one, qt3d change is being integrated right now)

**Comment by shr-project** [comment]
@migronof  can you please check v5.9.8 tags as well?

https://lists.qt-project.org/pipermail/announce/2019-April/000187.html

5.9.8 is already merged through https://github.com/meta-qt5/meta-qt5/pull/192 but most of the tags weren't downmerged yet.

**Comment by migronof** [comment]
Hi,
qt3d for 5.12.3 is fixed now.
For 5.9.8, only qtbase & qtvirtualkeyboard changefiles commits are missing from 5.9 branch. I'll look after them now. Should be fixed very very soon.

**Comment by shr-project** [comment]
Hi @migronof,

thanks for update, I've updated and merged #195 and create new one for v5.9.8 #196 (will keep that open until qtbase and qtvirtualkeyboard are done as well).

**Pull request closed without merging**
