### PR TITLE
qt5: Upgrade to Qt 5.13.0

### PR DESCRIPTION
**Pull request by sapiippo**
Update recipes for Qt 5.13.0, add new recipes for Qt modules
qtcoap and qtlottie, and remove qtcanvas3d.

Signed-off-by: Samuli Piippo <samuli.piippo@qt.io>

### CODE REVIEW

**Comment by shr-project** [comment]
I've added this to master-next, but seems to break:
maliit-framework-qt5 http://errors.yoctoproject.org/Errors/Build/83901/
maliit-plugins-qt5 http://errors.yoctoproject.org/Errors/Build/83902/
qt5-creator http://errors.yoctoproject.org/Errors/Build/83904/
qt5-opengles2-test http://errors.yoctoproject.org/Errors/Build/83900/

Please check them.

**Comment by shr-project** [comment]
Also some of the musl qtwebengine patches don't apply in this version, I've updated them here:
https://github.com/meta-qt5/meta-qt5/commit/c8b3085aa4b0030d6ef07b4703763692c2c58ec0

@kraj can you please check master-next with your musl builds? Thanks

**Comment by kraj** [comment]
Thanks for letting me know I will rebase my mut Branch and see how it pans out

**Comment by kraj** [comment]
@shr-project we need this patch https://github.com/meta-qt5/meta-qt5/pull/219 on top to get qtwenengine working on aarch64, I built it for aarch64/musl/clang and all looks ok

**Comment by sapiippo** [comment]
fix for creator build: https://github.com/meta-qt5/meta-qt5/pull/221
qt5-opengles2-test fails since gles2 is not enabled, but this is already excluded from world build

**Comment by kraj** [comment]
https://github.com/meta-qt5/meta-qt5/pull/220 is needed to fix qttools regression with clang

**Comment by shr-project** [comment]
In master now, thanks.

6463beab..53500ade  master -> master

**Pull request closed without merging**
