### PR TITLE
Upgrade to 5.12.2

### PR DESCRIPTION
**Pull request by migronof**
Contains Qt 5.12.2 submodule updates and following change touching
qmake5_base.bbclass & qtbase_git.bb:

    commit 713574b3e4932bb74bf8b4231d1fad67a086fbff
    Author: Samuli Piippo <samuli.piippo@qt.io>
    Date:   Thu Jan 10 16:18:05 2019 +0200

    qt5: patch build paths from installed files

    All 3rdparty libs and includes are now resolved into full filepaths,
    which means build paths to the yocto build environment are in module's
    prl, pri, pc and cmake files.

    Move existing patching from qtbase to the bbclass so that it's applied
    to all modules. -L paths are no longer included in the .pc files, remove
    unneeded patching for those.

    Task-number: QTBUG-72903

Change-Id: I51539e41e81caac5623cdfcdbe18bc132cdfe3a2
Signed-off-by: Mikko Gronoff <mikko.gronoff@qt.io>

### CODE REVIEW

**Comment by migronof** [comment]
qtopcua had some build errors, solution to similar case by Martin Jansa blatantly copied from qtwebengine recipe.

**Comment by shr-project** [comment]
Why not keep "qt5: patch build paths from installed files" separate commit?

**Comment by migronof** [comment]
No reason not to do that, actually. I just thought that as sapiippo upstreamed all the other patches already, I could just put all the diff there was left between Qt fork of meta-qt5 & this one to one commit - also "qt5: patch build paths from installed files" is mandatory for 5.12.1 onwards due changes in qtbase so they need to go together anyway. Surely I can submit them as separate if you prefer that way?

**Comment by shr-project** [comment]
please do

**Pull request closed without merging**
