### PR TITLE
qt5: upgrade to 5.11.3

### PR DESCRIPTION
**Pull request by migronof**
Includes qt submodule updates and following changes:

commit 4064b3b6ea53fb1ee1f9f96b06c6abe120b830f4
Author: Samuli Piippo <samuli.piippo@qt.io>
Date:   Tue Oct 30 16:34:51 2018 +0200

    qtdeclarative: fix inconsistent QML_COMPILE_HASH value
    
    qtdeclarative and qtdeclarative-native may end up with different values
    for QML_COMPILE_HASH, which prevents running QML application when
    qtquickcompiler has been used.

commit 8e485a2bfa4632bfefea861c2a06d9a6e8fc5c33
Author: Samuli Piippo <samuli.piippo@qt.io>
Date:   Wed Oct 3 12:00:02 2018 +0300

    qtbase: default to internal harfbuzz-ng    

    With -no-harfbuzz, Qt uses internal copy of harfbuzz-old, which is
    no longer maintained, and is extremely buggy. Instead, use the
    harfbuzz-ng version if systen harfbuzz is not used.

Signed-off-by: Mikko Gronoff <mikko.gronoff@qt.io>

### CODE REVIEW

**Comment by shr-project** [comment]
Cherry-picked to master-next and thud-next for build tests.

**Comment by otavio** [comment]
@migronof thanks for this; it is indeed good to keep the layer up to date. 

Next time, please send the pull request against master branch. We can backport it later after it gets merged into master.

This time, I changed the base of this pull request so we are good. :+1:

**Comment by cleitonbueno** [comment]
@shr-project I can test with the current version, but I remember that without this it broke the compilation.

**Comment by migronof** [comment]
To me it seemed that by the looks of it the
0001 patch was fixed with: https://codereview.qt-project.org/#/c/159856/ 
0002 patch was fixed with: https://codereview.qt-project.org/#/c/155158/ (QTBUG-52460)

Both in April-May 2016. The original patch was Dec 2015.

**Comment by shr-project** [comment]
Pushed to master and thud, thanks!
   9fc65c0..201fcf2  master -> master
   010a29e..201fcf2  thud -> thud

**Pull request closed without merging**
