### PR TITLE
qtpdf: Do not add -rtlib=libgcc -unwindlib=libgcc when using gcc

### PR DESCRIPTION
**Pull request by kraj**
We need to also check for compiler along with runtime to apply this
patch so we dont accidentally add these options when using TOOLCHAIN =
"gcc"

Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by shr-project** [comment]
The 2nd issue is probably caused by https://github.com/meta-qt5/meta-qt5/pull/481 which is in master-next, not re-ordering of .patches in SRC_URI after override change.

**Comment by kraj** [comment]
> The 2nd issue is probably caused by #481 which is in master-next, not re-ordering of .patches in SRC_URI after override change.

Ah yes I think I did rebase and fix at same time so missed the context where the change might have happened 

but I guess you wanted it rebased onto master-next anyway I suppose so perhaps all is good 

Would you prefer to update the comments in commit in the pull ? If so I can do that later today

**Comment by shr-project** [comment]
Thanks, no need to update anything from your side. If I take #481 I'll make sure all 3 patches in this area are updated in the same commit (so your 2nd commit from this PR won't be needed or be squashed into #481).

**Comment by shr-project** [comment]
Merged, thanks.

**Pull request closed without merging**
