### PR TITLE
qtlocation: add geoservices to PACKAGECONFIG

### PR DESCRIPTION
**Pull request by gvkalra**
Adding PACKAGECONFIG options.

### CODE REVIEW

**Comment by shr-project** [comment]
I've updated the commit message a bit when cherry-picking to master-next for CI.

It's missing your Signed-off-by please update the PR with that.

**Comment by gvkalra** [comment]
Done

**Comment by gvkalra** [comment]
I changed the commit message in this PR as well. Sorry about the 2 force-pushes.

**Comment by shr-project** [comment]
60e61ea2..8bc72a78  master -> master
   60e61ea2..8bc72a78  warrior -> warrior
Merged thanks.

**Pull request closed without merging**
