### PR TITLE
FIx pyqt5 build

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by shr-project** [comment]
Can you please rebase, so that there is just one commit to merge?

@balister Please review and test.

**Comment by schnitzeltony** [comment]
Are you sure that moving inherit  python3native python3-dir to common python-pyqt5.inc does not make python-pyqt5 same as python3-pyqt5?

**Comment by kraj** [comment]
Yes native dependencies are just for building they don’t have any bearing on runtime

**Comment by schnitzeltony** [comment]
I checked and this is wrong: sys.hexversion (the version of python running) is the a way pyqt decides to build for python2 or 3 variant. Just grep for sys.hexversion there are lot of 'if sys.hexversion >= 0x03000000:'. Your patch breaks python-pyqt5.

**Comment by kraj** [comment]
Ok this change is not necessary but rather a cleanup I will send a v2 without it

**Pull request closed without merging**
