### PR TITLE
Fix qt5-creator and qtwebkit builds with  QT 5.15+

### PR DESCRIPTION
**Pull request by kraj**
Update qtcreator to 4.12 which is required to get working with 5.15 even though 4.12 is still in RC1 phase
Use a more (5.212) maintained branch for qtwebkit, which is required to working it with QT 5.15

### CODE REVIEW

**Comment by shr-project** [comment]
@schnitzeltony please review the qtwebkit one

**Comment by schnitzeltony** [comment]
I cannot test it now (am on warrior & dunfell). If there is a later branch building with 5.15 and builds without python2 I am very happy about it. Thanks!

**Comment by shr-project** [comment]
@schnitzeltony meta-qt5/master (and master-next) is compatible with dunfell

OK, I'll merge it and we'll see who complains.

**Comment by kraj** [comment]
> I cannot test it now (am on warrior & dunfell). If there is a later branch building with 5.15 and builds without python2 I am very happy about it. Thanks!

yes it works with py3

**Comment by MatthewZMD** [comment]
Hope this gets merged soon.

**Comment by shr-project** [comment]
In master now.

**Pull request closed without merging**
