### PR TITLE
pyqtchart: Update to version 5.15.1 and use pypi

### PR DESCRIPTION
**Pull request by dagmcr**
Old version no longer available through riverbankcomputing.com.
Update to 5.15.1 and download the package sources using pypi class.

### CODE REVIEW

**Comment by dagmcr** [comment]
Sorry, I can see the commit is already in master:
https://github.com/meta-qt5/meta-qt5/commit/2f17a26d2f4c50458f5b1b145e4462853369b559

But will update it to use pypi class instead.

**Comment by dagmcr** [comment]
A similar example using PyPI class here:
https://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/recipes-devtools/python/python3-magic_0.4.18.bb#n12

**Comment by shr-project** [comment]
In master-next, thanks!

**Comment by shr-project** [comment]
and merged in master as well, thanks!

**Pull request closed without merging**
