### PR TITLE
qt5: upgrade to v5.15.11-lts-lgpl

### PR DESCRIPTION
**Pull request by fmntf**

### CODE REVIEW

**Comment by dolcini** [comment]
@fmntf @otavio : it looks like this PR broke the build:

```
01-08:05:22:42  ERROR: qtbase-5.15.11+git-r0 do_patch: Applying patch '0008-Replace-pthread_yield-with-sched_yield.patch' on target directory '/workdir/oe/tmp/work/armv8a-mx8mp-tdx-linux/qtbase/5.15.11+git/git'
01-08:05:22:42  CmdError('quilt --quiltrc /workdir/oe/tmp/work/armv8a-mx8mp-tdx-linux/qtbase/5.15.11+git/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0008-Replace-pthread_yield-with-sched_yield.patch
01-08:05:22:42  patching file tests/auto/corelib/kernel/qmetatype/tst_qmetatype.cpp
01-08:05:22:42  Hunk #2 FAILED at 369.
01-08:05:22:42  1 out of 2 hunks FAILED -- rejects in file tests/auto/corelib/kernel/qmetatype/tst_qmetatype.cpp
01-08:05:22:42  patching file tests/auto/network/socket/qtcpsocket/tst_qtcpsocket.cpp
01-08:05:22:42  Hunk #2 FAILED at 2201.
01-08:05:22:42  1 out of 2 hunks FAILED -- rejects in file tests/auto/network/socket/qtcpsocket/tst_qtcpsocket.cpp
01-08:05:22:42  Patch 0008-Replace-pthread_yield-with-sched_yield.patch does not apply (enforce with -f)
01-08:05:22:42  
01-08:05:22:42  stderr: ')
01-08:05:22:42  ERROR: Logfile of failure stored in: /workdir/oe/tmp/work/armv8a-mx8mp-tdx-linux/qtbase/5.15.11+git/temp/log.do_patch.343250
01-08:05:22:42  NOTE: recipe qtbase-5.15.11+git-r0: task do_patch: Failed
01-08:05:22:42  ERROR: Task (/workdir/oe/build/../layers/meta-qt5/recipes-qt/qt5/qtbase_git.bb:do_patch) failed with exit code '1'
01-08:05:22:42  NOTE: recipe gtk+3-3.24.38-r0: task do_configure: Started
01-08:05:22:45  WARNING: qtbase-native-5.15.11+git-r0 do_fetch: Failed to fetch URL git://code.qt.io/qt/qtbase.git;name=qtbase;branch=5.15;protocol=git, attempting MIRRORS if available
01-08:05:23:00  NOTE: recipe gstreamer1.0-plugins-base-1.22.0.imx-r0: task do_configure: Succeeded
01-08:05:23:00  NOTE: recipe gtk+3-3.24.38-r0: task do_configure: Succeeded
01-08:05:23:01  NOTE: recipe librsvg-2.56.3-r0: task do_configure: Succeeded
01-08:05:23:14  NOTE: recipe json-glib-1.8.0-r0: task do_compile: Succeeded
01-08:05:23:32  NOTE: recipe libsoup-2.4-2.74.3-r0: task do_compile: Succeeded
01-08:05:24:28  ERROR: qtbase-native-5.15.11+git-r0 do_fetch: Fetcher failure: Unable to find revision c1f8fa2578d99e07f5e581f26bd532695b9534f9 in branch 5.15 even from upstream
01-08:05:24:28  ERROR: qtbase-native-5.15.11+git-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://code.qt.io/qt/qtbase.git;name=qtbase;branch=5.15;protocol=git')
01-08:05:24:28  ERROR: Logfile of failure stored in: /workdir/oe/tmp/work/x86_64-linux/qtbase-native/5.15.11+git/temp/log.do_fetch.173299
01-08:05:24:28  NOTE: recipe qtbase-native-5.15.11+git-r0: task do_fetch: Failed
01-08:05:24:28  ERROR: Task (/workdir/oe/build/../layers/meta-qt5/recipes-qt/qt5/qtbase-native_git.bb:do_fetch) failed with exit code '1'
```

cc: @MaxKrummenacher

**Comment by otavio** [comment]
Hello @fmntf, are you currently working on a fix for the issue or do we need to revert back to a previous version?

**Comment by fmntf** [comment]
Hello Otavio, please revert the PR. I will eventually redo the work against 5.15.12. Thank you!

**Comment by fmntf** [comment]
Hello @otavio, please have a look on https://github.com/meta-qt5/meta-qt5/pull/550
Thank you,
Francesco

**Pull request merged**
