### PR TITLE
qtwebengine: fix statx syscalls

### PR DESCRIPTION
**Pull request by andy9a9**
Correctly handle statx syscalls

Patch has been taken from https://bugreports.qt.io/browse/QTBUG-103969

Signed-off-by: Andrej Valek <andrej.valek@siemens.com>

### CODE REVIEW

**Comment by shr-project** [comment]
I don't use qtwebengine anywhere now, can you please test https://github.com/meta-qt5/meta-qt5/pull/476 (I haven't even build tested it yet, but was planing to bump to v5.15.10-lts and the patch you need is included in 87-based branch as well now).

**Comment by andy9a9** [comment]
I've tested it with 5.15.9-lts, where it works fine. If I look at the latest commit here https://github.com/qt/qtwebengine/commits/5.15.10 , chromium submodule is pointing to older revision. It was merged 12-days ago https://github.com/qt/qtwebengine-chromium/commits/87-based .

So does it mean, that we don't need this patch, just wait for new "rebase"?

**Comment by shr-project** [comment]
> So does it mean, that we don't need this patch, just wait for new "rebase"?

You mean this "rebase"?
https://github.com/meta-qt5/meta-qt5/pull/476/commits/ba332a34b14dcd8aa4247963f9d783bc8907b5e7

**Comment by shr-project** [comment]
> Exactly ;) So this could be close then, right?

If my PR works for you, then yes, but I haven't even build tested it yet and don't have any test setup for runtime testing as I have no use for qtwebengine anymore.

**Comment by andy9a9** [comment]
I have tested it with 5.15.9-tls, can't say about 5.15.10-lts, but hopefully it works.

Maybe I can test it, but only at next month if nobody else will do that.

**Comment by shr-project** [comment]
OK, then I'll merge it after build-test and hope for best.

**Pull request closed without merging**
