### PR TITLE
QtWebengine fixes

### PR DESCRIPTION
**Pull request by schnitzeltony**

### CODE REVIEW

**Comment by shr-project** [comment]
Thanks

> while at it: renumber patches. To be sure not to ruin musl patches, a   'bitbake -cpatch qtwebengine' with musl active was done

I've dropped this part from your last commit and instead added different commit on top in master-next, because the icu patch needs different rework and I didn't want to renumber patches twice in 2 subsequent meta-qt5 commits, please review it in master-next.

**Comment by schnitzeltony** [comment]
If understand master-next correctly, you have
* put icu patch to chromium - yes that's where it belongs
* refreshed it - and also yes this always a good thing. Off-topic: did you use devtool? I ask this because devtool is broken for me currently
Thanks for keeping things in order

**Comment by shr-project** [comment]
Correct + adjusted patchdir in your patch.

For meta-qt5 I don't use devtool, because I keep the branches in https://github.com/meta-qt5/qt* forks where it's easier to rebase them on new version from upstream and then just "git format-patch --no-numbered --no-signature" to refresh the .patch files in meta-qt5.

Sometimes it goes out of sync when I merge some meta-qt5 PR without properly refreshing meta-qt5/qt* forks (like with the icu patch).

> I ask this because devtool is broken for me currently

The issue with _PYTHON_SYSCONFIGDATA_NAME (as in https://lists.openembedded.org/g/openembedded-core/message/141905) or something else?

**Comment by schnitzeltony** [comment]
> The issue with _PYTHON_SYSCONFIGDATA_NAME (as in https://lists.openembedded.org/g/openembedded-core/message/141905) or something else?

The level of annoyance turned too high so I looked into: Yes that one fixes it - thanks.

**Comment by shr-project** [comment]
Merged thanks
   23f78f70..b7255751  master -> master

**Pull request closed without merging**
