### PR TITLE
Remove PyQt_qreal_double from DISABLED_FEATURES

### PR DESCRIPTION
**Pull request by temap**
Since Qt 5.2.0 the qreal is double (see change [d8bf317546bc](https://github.com/qt/qtbase/commit/d8bf317546bcfab0b6b50375218429fa9d470705) in qtbase.git).

### CODE REVIEW

**Comment by shr-project** [comment]
I've applied this manually, now in master-next.

**Comment by temap** [comment]
@shr-project thanks. Could you also cherry-pick into zeus-next?

**Comment by shr-project** [comment]
Merged in master and zeus:
0bdbb344..6a9c0acb  zeus -> zeus

**Comment by temap** [comment]
Hi @shr-project could you cherry-pick https://github.com/meta-qt5/meta-qt5/pull/289/commits/376a4ec56e495a28673c37af795a30a8691dd942? It was not cherry-picked on zeus and zeus-next, I still have the issue with floats without these patch.

**Comment by shr-project** [comment]
Sorry, should be in zeus now:
6a9c0acb..b6767f3b  zeus -> zeus

**Comment by temap** [comment]
@shr-project thank you.

**Pull request closed without merging**
