### PR TITLE
Revert "icu: use system library only targets"

### PR DESCRIPTION
**Pull request by schnitzeltony**
1. It breaks build:
| ERROR at //third_party/icu/BUILD.gn:10:1: Unable to load "/home/amuller/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-mortsgna-linux-gnueabi/qtwebengine/5.15.0+gitAUTOINC+f526855509_7b2f027ea8-r0/git/src/3rdparty/chromium/v8/snapshot_toolchain.gni".
| import("//v8/snapshot_toolchain.gni")
| ^-----------------------------------
| See //url/BUILD.gn:97:15: which caused the file to be included.
|     deps += [ "//third_party/icu" ]
|               ^------------------
| Project ERROR: GN run error!
| make[2]: *** [Makefile:82: sub-gn_run-pro-make_first] Error 3

and revert fixes build again

2. Message of commit says:
    Complete system ICU library using requires ICU dev package be installed
    on host.
At least in my environment this is not true: My host does not have
libicu-devel installed and qtwebengine builds perfectly fine.

This reverts commit c9553a5d2b5fd113dd5c165f2bd47618908528a9.

### CODE REVIEW

**Comment by shr-project** [comment]
In master-next for testing.

**Comment by andy9a9** [comment]
@shr-project Why are you going to remove it, while we don't have any response on my questions?

**Comment by shr-project** [comment]
it's in master-next "for testing" I'm going to run many builds with this included and hopefully in the meantime @schnitzeltony will be able to respond.

**Comment by schnitzeltony** [comment]
Am busy at other ends (and building qtwebengine is a time eater) so sorry for not responding yet. Although the questions asked confused me slightly (e.g Android?) here some more information:

* Am building on Linux build host (Fedora 32)
* Builds are for ARM cortex A7 (although this should not make any difference - crash is on native build part)
* PACKAGECONFIG is default (have pulseaudio in DISTRO_FEATURES) - no icu:

> [amuller@superandy oe-core]$ bitbake -e qtwebengine | grep ^PACKAGECONFIG
> PACKAGECONFIG="libwebp libevent libpng                    pulseaudio"
> PACKAGECONFIG_CONFARGS=" -no-feature-webengine-system-ffmpeg -no-feature-webengine-system-glib -no-feature-webengine-system-harfbuzz -no-feature-webengine-system-icu -no-feature-webengine-system-jsoncpp -feature-webengine-system-libevent -feature-webengine-system-png -no-feature-webengine-system-libvpx -feature-webengine-system-libwebp -no-feature-webengine-system-libxml2 -no-feature-webengine-system-minizip -no-feature-webengine-system-opus -no-feature-webengine-pepper-plugins -no-feature-webengine-printing-and-pdf -no-feature-webengine-proprietary-codecs -no-feature-webengine-system-protobuf -feature-webengine-pulseaudio -no-feature-webengine-spellchecker -no-feature-webengine-webrtc -no-feature-webengine-system-zlib"
> PACKAGECONFIG_OPENSSL="openssl"
> 

As soon as I find time, I'll try builds with icu in packageconfig with / without revert and supply full logs.

Haven't looked into further but is it possible that re-adding icu to depends might do the trick?

Ahh and what I am missing here: Where can I find the error logs that the patch to revert fixes? The only logs I found were with modifications done already.

**Comment by andy9a9** [comment]
All problems, what I've founded are mentioned in #304 .
- If you want to use external `icu` library, than you should enable icu via `PACKAGECONFIG`.
- If you want to use bundled `icu`, keep the default `PACKAGECONFIG`. In this case, it cant' be depending on external `icu` headers/libraries. (This case I fixed it.)

Logs what I want to see should be in `/home/amuller/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-mortsgna-linux-gnueabi/qtwebengine/5.15.0+gitAUTOINC+f526855509_7b2f027ea8-r0/temp`. It depends on, which task failed, probably configure or compile. So put the file `log.do_configure` or `log.do_compile` here please, than we can analyze, what's wrong there.

**Comment by schnitzeltony** [comment]
Without icu in packageconfig:

[log.do_compile.txt](https://github.com/meta-qt5/meta-qt5/files/5148711/log.do_compile.txt)
[log.do_configure.txt](https://github.com/meta-qt5/meta-qt5/files/5148712/log.do_configure.txt)

**Comment by andy9a9** [comment]
> Without icu in packageconfig:
> 
> [log.do_compile.txt](https://github.com/meta-qt5/meta-qt5/files/5148711/log.do_compile.txt)
> [log.do_configure.txt](https://github.com/meta-qt5/meta-qt5/files/5148712/log.do_configure.txt)

Looks like, that problematic file is `snapshot_toolchain.gni`. But from the log, I can't really understand, if it's problem with file, for couldn't not be found.

1. Let's try to find the right location for this file and paste it here.
2. Search for other lines with the same import. Are there any?
3. I saw somewhere a different usage. What about this one `import("//v8/gni/snapshot_toolchain.gni")`? Try to hange it in `third_party/cu/BUILD.gn`.

**Comment by schnitzeltony** [comment]
Have tried latest master environment:

* Still same build error without icu in PACKAGECONFIG
* Just re-adding icu to DEPENDS does not fix
* Ahh and I completely forgot to mention: The magic patch (still have no idea what it is supposed to fix) does not apply cleanly:

> Applying patch 0005-icu-use-system-library-only-targets.patch
> patching file src/3rdparty/chromium/third_party/icu/BUILD.gn
> Hunk #3 succeeded at 1217 with fuzz 1 (offset 70 lines).
> Hunk #4 succeeded at 1430 (offset 74 lines).
> Hunk #5 succeeded at 1438 (offset 74 lines).
> Hunk #6 succeeded at 1450 (offset 74 lines).
> 
> The context lines in the patches can be updated with devtool:
> 
>     devtool modify qtwebengine
>     devtool finish --force-patch-refresh qtwebengine <layer_path>
> 
> Don't forget to review changes done by devtool!
>

**Comment by schnitzeltony** [comment]
Just out of curiosity: It does not build for me WITH 'icu' in PACKAGECONFIG either

[log.do_compile.txt](https://github.com/meta-qt5/meta-qt5/files/5179939/log.do_compile.txt)
[log.do_configure.txt](https://github.com/meta-qt5/meta-qt5/files/5179940/log.do_configure.txt)

**Comment by andy9a9** [comment]
> Just out of curiosity: It does not build for me WITH 'icu' in PACKAGECONFIG either
> 
> [log.do_compile.txt](https://github.com/meta-qt5/meta-qt5/files/5179939/log.do_compile.txt)
> [log.do_configure.txt](https://github.com/meta-qt5/meta-qt5/files/5179940/log.do_configure.txt)

Ok, so there is the same error, with the toolchain. Please try the steps which I mentioned previously https://github.com/meta-qt5/meta-qt5/pull/351#issuecomment-683677444 .

**Comment by schnitzeltony** [comment]
Yes you asked me things of which most you could have done yourself (you have same sources - right?)

The import introduced in 0005-icu-use-system-library-only-targets.patch is missing '/gni' in its path. Created patches for this and for the patch fuzz. Once tested with & without 'icu' in PACKAGECONFIG I will send an alternate PR.

So close this one - and am still wondering how this worked for others...

**Pull request closed without merging**
