### PR TITLE
enable framebuffer rotation

### PR DESCRIPTION
**Pull request by embetrix**

### CODE REVIEW

**Comment by shr-project** [comment]
As meta-qt5 is dead-end, can you please get it merged upstream first into qtbase-6, so that it doesn't die with meta-qt5?

**Comment by embexus** [comment]
@shr-project last commit is 1 week old!

I will try to upstream this patch then

**Comment by embexus** [comment]
@shr-project it doesn't look like dead !!

**Comment by shr-project** [comment]
I said _dead-end_ as there won't be another qt5 release and even the regular LTS updates for 5.15 are available only for commercial users (from TQC fork of meta-qt5).

**Comment by embexus** [comment]
@shr-project I don't get then the reason why this PR is not accepted ?! it's not a new feature but a bug fix

**Review by paletteguy — APPROVED** [review]
Looks good.

**Comment by shr-project** [comment]
Qt5 is dead please follow up with TQC for their meta-qt6 if you're still interested.

**Pull request closed without merging**
