### PR TITLE
layer: Mark zeus as compatible release

### PR DESCRIPTION
**Pull request by kraj**
Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by kraj** [comment]
This needs to merge in quickly, its breaking all CI builds on master otherwise

**Comment by shr-project** [comment]
Sorry I thought I did merge it immediately and I did, but only to warrior
branch.

**Comment by kraj** [comment]
and also into master please

**Comment by shr-project** [comment]
Done for master and zeus.

**Pull request merged**
