### PR TITLE
Update to Qt 5.14.0

### PR DESCRIPTION
**Pull request by sapiippo**
This brings Qt 5.14.0 and all other changes done in our mirror in Qt codereview.

### CODE REVIEW

**Comment by shr-project** [comment]
ThanksRebased on top of master-next and pushed there:
e8221c2c..a9036ee7  master-next -> master-next

Please check it.

**Comment by sapiippo** [comment]
one of the webengine musl patches is still wrong, I’ll try to update this still today

**Comment by shr-project** [comment]
There are few issues reported by @khem yesterday:

1) qtbase.do_configure failed for him with eglfs enabled:
http://errors.yoctoproject.org/Errors/Details/306054/
(JaMa: built ok in my first test build with x11, maybe he overcame this issue already)

2) I dont see the build progress bar with qtbase 5.14

3) with ptests enabled I am seeing a hang on tst_qnetworkcookie.cpp
perhaps thats just my gcc10

4) btw. clang is far better in build performance and runtime perf for qt5
(JaMa: not an issue, but worth mentioning here :))

JaMa:
I've also updated the qtbase patches to apply cleanly and uploaded them to meta-qt5

qtwebengine patches are worse
0023-chromium-Move-CharAllocator-definition-to-a-header-f.patch doesn't apply anymore
ERROR: qtwebengine-5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0 do_patch: Command Error: 'quilt --quiltrc /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0023-chromium-Move-CharAllocator-definition-to-a-header-f.patch
patching file chromium/cc/base/list_container_helper.cc
Hunk #1 FAILED at 13.
1 out of 1 hunk FAILED -- rejects in file chromium/cc/base/list_container_helper.cc
patching file chromium/cc/base/list_container_helper.h
Hunk #1 FAILED at 8.
Hunk #2 succeeded at 174 with fuzz 1.
1 out of 2 hunks FAILED -- rejects in file chromium/cc/base/list_container_helper.h
Patch 0023-chromium-Move-CharAllocator-definition-to-a-header-f.patch does not apply (enforce with -f)
ERROR: Logfile of failure stored in: /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/qtwebengine/5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0/temp/log.do_patch.21067
NOTE: recipe qtwebengine-5.14.0+gitAUTOINC+d366f1d5d3_939daf833f-r0: task do_patch: Failed
ERROR: Task (/OE/build/oe-core/meta-qt5/recipes-qt/qt5/qtwebengine_git.bb:do_patch) failed with exit code '1'

musl-specific 0004-mkspecs-Allow-builds-with-libc-glibc.patch doesn't apply at all, because the modified mkspecs/features/configure.prf was dropped completely in:
commit 047d61f188aae3fe3ebc689900b8a5c9fb6e901d
Author: Michal Klocek <michal.klocek@qt.io>
Date:   Fri Aug 9 17:40:29 2019 +0200

    Add webengine-core feature

The same chunk can be found in src/buildtools/config/support.pri, so I've updated the .patch accordingly, but haven't tried the build with musl yet.

Fixes for the patches added to master-next, but build is still going (it will be a while on my slow builder)

**Comment by shr-project** [comment]
Merged in master, but please check remaining issues reported here.

**Comment by sapiippo** [comment]
on the remaining issues:

1) looks weird combination with args "-no-eglfs -opengl desktop -qpa eglfs". We are internally building eglfs configurations without issues.

2) WebEngine still has the build progress bar, I don't think any other module has ever had it.

3) Haven't seen that with the default gcc9 from poky/master

**Pull request closed without merging**
