### PR TITLE
Native QTHelp tools + target devel enhancements

### PR DESCRIPTION
**Pull request by schnitzeltony**
Burned down my build machine on this. Hope it's good enough now...

### CODE REVIEW

**Comment by shr-project** [comment]
All in master-next except the last commit with qt5-creator upgrade, because Khem's PR has an upgrade to even newer version https://github.com/meta-qt5/meta-qt5/pull/344/commits/143863d0dd385c508c262d3fdc43bb54fc583fa7

Please check that.

**Comment by schnitzeltony** [comment]
I'll check Khems upgrade - missed that - thanks.

Out of curiosity: In case these patches don't cause undetected trouble (burned down my build machine for tests...): Would a backport to dunfell have a chance?  Background am looking for the QtHelp thingy for VERY long time..

**Comment by shr-project** [comment]
I don't mind backporting this to dunfell, but I don't use qt5-creator nor devel on target, so I would appreciate input from other meta-qt5 users on this.

**Comment by shr-project** [comment]
In master now
   5144a99a..23f78f70  master -> master

**Pull request closed without merging**
