### PR TITLE
qt5/qttools: Install qdbus

### PR DESCRIPTION
**Pull request by alistair23**
Signed-off-by: Alistair Francis <alistair.francis@wdc.com>

### CODE REVIEW

**Comment by alistair23** [comment]
I'm not sure what you mean, it wasn't previously being installed. Are qmake rules something that should be changed?

**Comment by otavio** [comment]
It should be handled by the build script of qttools as the rest of the installed tools.

**Comment by otavio** [comment]
@alistair23 please check if it is inside `${bindir}/qt5`, as suggested by @sapiippo

**Comment by alistair23** [comment]
I don't see it:

# ls /bin/
ash		  dmesg		      login.shadow	     ping6		   systemd-escape
base64		  dmesg.util-linux    loginctl		     ps			   systemd-firstboot
bash		  dnsdomainname       ls		     ps.procps		   systemd-hwdb
bash.bash	  dumpkmap	      ls.coreutils	     pwd		   systemd-inhibit
busybox		  echo		      lsmod		     pwd.coreutils	   systemd-machine-id-setup
busybox.nosuid	  echo.coreutils      lsmod.kmod	     rm			   systemd-notify
busybox.suid	  egrep		      machinectl	     rm.coreutils	   systemd-sysusers
cat		  false		      mkdir		     rmdir		   systemd-tmpfiles
cat.coreutils	  false.coreutils     mkdir.coreutils	     rmdir.coreutils	   systemd-tty-ask-password-agent
chattr		  fgrep		      mknod		     run-parts		   tar
chattr.e2fsprogs  getopt	      mknod.coreutils	     sed		   touch
chgrp		  grep		      mktemp		     sh			   touch.coreutils
chgrp.coreutils   gunzip	      more		     sleep		   true
chmod		  gzip		      more.util-linux	     sleep.coreutils	   true.coreutils
chmod.coreutils   hostname	      mount		     stat		   udevadm
chown		  hostname.coreutils  mount.util-linux	     stat.coreutils	   umount
chown.coreutils   journalctl	      mountpoint	     stty		   umount.util-linux
cp		  kill		      mountpoint.util-linux  stty.coreutils	   uname
cp.coreutils	  kill.coreutils      mv		     su			   uname.coreutils
cpio		  kill.procps	      mv.coreutils	     su.shadow		   usleep
date		  kill.util-linux     netstat		     su.util-linux	   vi
date.coreutils	  kmod		      networkctl	     sync		   watch
dd		  ln		      pidof		     sync.coreutils	   watch.procps
dd.coreutils	  ln.coreutils	      pidof.procps	     systemctl		   zcat
df		  login		      ping		     systemd-ask-password

# ls /bin/qt5
ls: cannot access '/bin/qt5': No such file or directory

# ls /usr/bin/qt 
ls: cannot access '/usr/bin/qt': No such file or directory

**Comment by alistair23** [comment]
find -name "qdbus" doesn't find anything either.

**Comment by otavio** [comment]
and:

```
ls /usr/bin/qt5
```
?

**Comment by alistair23** [comment]
I checked that as well, same problem

# ls /usr/bin/qt5
ls: cannot access '/usr/bin/qt5': No such file or directory

**Comment by sapiippo** [comment]
Just to verify that you have qttools-tools package installed?

**Comment by otavio** [comment]
We did a local test here. Checking the contents of the binary package it shows:

```
% bitbake qttools
...
% ye pv qttools-tools | grep dbus
-rwxr-xr-x root/root     67632 2018-07-03 14:41 ./usr/bin/qt5/qdbus
-rwxr-xr-x root/root    114204 2018-07-03 14:41 ./usr/bin/qt5/qdbusviewer
```

So you are likely not installing `qttools-tools` package inside your image.

**Comment by alistair23** [comment]
I don't have qttools-tools installed on the host. I'll check the image and see if I'm missing anything

**Pull request closed without merging**
