### PR TITLE
pyqt5: Upgrade to 5.13.2 and fix qtwebengine build on musl

### PR DESCRIPTION
**Pull request by kraj**
Blacklist py2 version, it does not build and py2 is on its way out in
Jan 2020 anyway

Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by shr-project** [comment]
In master-next for testing, thanks.

**Comment by schnitzeltony** [comment]
@kraj: Please don't push on top of branches you sent pull requests with because watching users get (multiple) notifications each time you do - thanks

**Comment by kraj** [comment]
stop watching then

**Comment by schnitzeltony** [comment]
I don't want to miss something just because you do things wrong - but keep on going...

**Comment by kraj** [comment]
this pull should be against `mater-next` somehow it ends up against `master`, I will close this one.

**Pull request closed without merging**
