### PR TITLE
qt5: partial fix for v5.9.8 tags

### PR DESCRIPTION
**Pull request by shr-project**
* waiting for qtbase and qtvirtualkeyboard to be finished as well

### CODE REVIEW

**Comment by shr-project** [comment]
@migronof any update on qtbase 5.9 branch? I would like to close this

**Comment by migronof** [comment]
qtvirtualkeyboard is done but qtbase merge has failed several times. I'll try to hurry that as it has been untouched since the weekend.

**Comment by shr-project** [comment]
I've already updated qtvirtualkeyboard few days ago in this PR, so yes qtbase is the last one.

**Comment by shr-project** [comment]
qtbase done now as well, will merge after a build

**Comment by migronof** [comment]
Qtbase is now finally merged.

**Pull request merged**
